REM   Script: ERRO NO COMUM
REM   ADMIN FINALIZADO

CREATE TABLE USUARIO( 
	CPF VARCHAR(15) , 
	NOME VARCHAR(100) NOT NULL, 
	EMAIL VARCHAR(60) NOT NULL, 
	TELEFONE1 VARCHAR(10), 
	TELEFONE2 VARCHAR(10), 
	END_RUA VARCHAR(100), 
	END_NUM VARCHAR(100), 
	END_CEP VARCHAR(100), 
	CPF_CONVIDADO VARCHAR(15), 
	CONSTRAINT PK_USUARIO PRIMARY KEY (CPF), 
	CONSTRAINT FK_CPF_CONVIDADO FOREIGN KEY (CPF_CONVIDADO) REFERENCES USUARIO(CPF) 
);

CREATE TABLE ARTISTA( 
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, 
	NOME VARCHAR(100), 
	CONSTRAINT PK_ARTISTA PRIMARY KEY (ID) 
);

CREATE TABLE GRAVADORA( 
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, 
	NOME VARCHAR(100), 
	CONSTRAINT PK_GRAVADORA PRIMARY KEY (ID) 
);

CREATE TABLE INSTRUMENTO( 
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, 
	NOME VARCHAR(100), 
	CONSTRAINT PK_INSTRUMENTO PRIMARY KEY (ID) 
);

CREATE TABLE ORGANIZACAO( 
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, 
	NOME VARCHAR(100), 
	CONSTRAINT PK_ORGANIZACAO PRIMARY KEY (ID) 
);

CREATE TABLE CATEGORIA( 
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, 
	NOME VARCHAR(100), 
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID) 
);

CREATE TABLE MUSICA( 
	ID INT, 
	NUM INT, 
	NOME VARCHAR(100), 
	GENERO VARCHAR(100), 
	CONSTRAINT PK_MUSICA PRIMARY KEY (ID, NUM), 
	CONSTRAINT ID_MUSICA FOREIGN KEY (ID) REFERENCES GRAVADORA ON DELETE CASCADE 
);

CREATE TABLE ADMIN_ ( 
 
	ID VARCHAR(15), 
	CARGO VARCHAR(100), 
	CONSTRAINT FK_ID_ADMIN FOREIGN KEY (ID) REFERENCES USUARIO(CPF), 
	CONSTRAINT PK_ADMIN PRIMARY KEY (ID) 
 
);

CREATE TABLE COMUM( 
 
	ID VARCHAR(15), 
	CONSTRAINT FK_ID_COMUM FOREIGN KEY (ID) REFERENCES USUARIO(CPF), 
	CONSTRAINT PK_COMUM PRIMARY KEY (ID) 
 
);

CREATE TABLE CANTA( 
	ID INT, 
    NUM INT, 
    ID_ART INT, 
    CONSTRAINT ID_MUSICA_CANTA FOREIGN KEY (ID,NUM) REFERENCES MUSICA (ID,NUM), 
    CONSTRAINT ID_ARTISTA_CANTA FOREIGN KEY (ID_ART) REFERENCES ARTISTA (ID), 
	CONSTRAINT PK_CANTA PRIMARY KEY (ID, NUM, ID_ART) 
);

CREATE TABLE CONSOME( 
 
	CPF VARCHAR(15), 
	ID INT, 
	NUM INT, 
	DATA_ TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT CPF_CONSOME FOREIGN KEY (CPF) REFERENCES USUARIO(CPF), 
	CONSTRAINT ID_MUSICA_CONSOME FOREIGN KEY (ID, NUM) REFERENCES MUSICA(ID,NUM), 
	CONSTRAINT PK_CONSOME PRIMARY KEY (CPF,ID) 
 
);

CREATE TABLE TOCA(

  ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	ID_CANTA INT,
	ID_INSTRUMENTO INT,
	ID_MUS INT,
	ID_NUM INT,
	CONSTRAINT FK_ID_CANTA FOREIGN KEY (ID_CANTA,ID_NUM,ID_MUS) REFERENCES CANTA(ID, NUM, ID_ART),
	CONSTRAINT FK_ID_INSTRUMENTO FOREIGN KEY (ID_INSTRUMENTO) REFERENCES INSTRUMENTO(ID),
	CONSTRAINT PK_TOCA PRIMARY KEY (ID)

);;

CREATE TABLE GANHA( 
 
	ID_CATEGORIA INT, 
	ID_ORGANIZACAO INT, 
	DATA_ TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	ID_MUSICA INT NOT NULL, 
	ID_NUM INT NOT NULL, 
 
	CONSTRAINT FK_ID_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID), 
	CONSTRAINT FK_ID_ORGANIZACAO FOREIGN KEY (ID_ORGANIZACAO) REFERENCES ORGANIZACAO(ID), 
	CONSTRAINT NOTNULL_ID_MUSICA FOREIGN KEY (ID_MUSICA,ID_NUM) REFERENCES MUSICA(ID,NUM), 
	CONSTRAINT PK_GANHA PRIMARY KEY (ID_CATEGORIA,ID_ORGANIZACAO,DATA_) 
);

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('96728388178','George Fischer','gravida@aol.com','31137-6247','7684 Ornare Av.','25251-171','645','72653-7204');

CREATE OR REPLACE TRIGGER trigger_usuario 
BEFORE INSERT ON USUARIO 
FOR EACH ROW 
DECLARE 
  cpf_convidado USUARIO.CPF_CONVIDADO%TYPE; 
BEGIN 
 -- Seleciona um CPF aleatório existente na tabela USUARIO 
    IF :NEW.CPF_CONVIDADO IS NULL THEN  
        SELECT CPF INTO cpf_convidado FROM ( 
            SELECT CPF FROM USUARIO WHERE CPF <> :NEW.CPF ORDER BY DBMS_RANDOM.RANDOM) 
        WHERE ROWNUM = 1; 
 
        -- Atribui o CPF selecionado à coluna CPF_CONVIDADO do novo registro 
        :NEW.CPF_CONVIDADO := cpf_convidado; 
    END IF; 
END; 
/

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('38272418683','Tate Huber','neque@yahoo.edu','73775-5557','567-6538 Bibendum Road','84676-195','175','82245-3899');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('66568769263','Lillith Mercer','et.lacinia@google.net','68473-8015','Ap #432-569 Et Av.','58227-477','923','18977-7273');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('98773832628','Blake Cotton','ridiculus.mus.proin@outlook.net','56776-5171','Ap #414-5894 Egestas. Ave','91545-177','758','13708-8486');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('14658923297','Dieter Tanner','urna.justo@google.net','37117-2716','P.O. Box 511, 3676 Nonummy Rd.','86068-482','682','27655-9683');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('51672289875','Jared Santana','nunc.sed@icloud.edu','15465-1248','325-7455 Lorem, St.','18128-642','372','45185-1656');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('59317743778','Herman Payne','pellentesque.ultricies@protonmail.org','80935-4525','Ap #517-3982 Pellentesque Street','65874-494','931','88361-1171');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('28453274274','Emerson Ochoa','phasellus.nulla@hotmail.net','48653-9933','Ap #682-2149 Eget Av.','25042-822','811','06393-1832');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('97588314932','Garrett Fitzpatrick','eros.nec@yahoo.couk','96207-7365','2801 Consequat St.','13400-767','682','57442-1573');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('48491585487','Carl Chapman','donec.tincidunt.donec@protonmail.ca','63552-1428','Ap #808-8432 Urna. Rd.','45668-482','627','13330-2432');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('58648837498','Fleur Church','phasellus.libero.mauris@hotmail.com','63768-5880','Ap #321-9418 Eget Rd.','61534-223','613','12878-8068');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('27565652844','Aaron Johnston','vulputate.dui.nec@hotmail.ca','96227-7320','8330 Tristique Rd.','65457-837','412','45225-4053');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('97237695877','Gretchen Lawrence','suspendisse.tristique@protonmail.edu','87688-1951','371-302 Aptent Rd.','92184-804','313','14790-8251');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('94147467348','Brittany Pollard','nunc@yahoo.org','47696-6513','Ap #621-2127 Tempor, Rd.','86242-272','774','33120-1163');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('61272925396','Leandra Newman','integer.tincidunt@icloud.com','92123-5214','991-7602 Eu Rd.','66684-242','478','23423-8703');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('77843428477','Talon Jenkins','suscipit@google.net','50274-1879','451-4772 Nascetur St.','17286-636','987','98344-6763');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('76543844622','Morgan Saunders','eu.euismod.ac@aol.couk','46510-0765','346-8593 Ante. Avenue','12806-634','955','63750-4418');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('64531223549','Leslie French','eu@protonmail.com','72381-2891','Ap #643-7161 In St.','62737-114','917','54218-1474');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('45782635435','Molly Sharp','sem.consequat@icloud.edu','82366-2825','Ap #997-7882 Parturient Ave','15184-381','425','38126-2164');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('23279179463','Lyle Sargent','montes.nascetur@yahoo.org','59617-6225','6603 Sollicitudin Avenue','35077080','229','32867-1728');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('46575854216','Zelda Nelson','dictum.augue.malesuada@yahoo.ca','22857-5784','442-4138 Sem Rd.','66253-133','267','17795-4052');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('84766347538','Colby Fox','id.blandit@hotmail.edu','67189-7561','627-5697 Sit Rd.','56802-683','150','02368-2807');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('85826836446','Gray Adams','tempor.augue@hotmail.org','90120-6364','P.O. Box 992, 1311 Sit Avenue','33718817','847','20309-6532');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('45638947443','Amal Marsh','at.nisi@outlook.couk','88001-8339','834-6515 Amet Av.','68427-315','834','60222-8318');

INSERT INTO USUARIO (CPF,NOME,EMAIL,TELEFONE1,END_RUA,END_CEP,END_NUM,TELEFONE2) 
VALUES ('38994364827','Ina Weeks','metus.in@icloud.net','26344-6779','Ap #564-4527 Egestas Street','98757-661','779','14440-8244');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Música de Reggae');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Música de Rock');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Música de Pop');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Música de Rap');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Música de Funk');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Música Eletrônica');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Música de Forró');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Clipe');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Performance');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Vocal');

INSERT INTO CATEGORIA (NOME) 
VALUES ('Melhor Cover');

INSERT INTO ARTISTA (NOME) 
VALUES ('Maisie Blevins');

INSERT INTO ARTISTA (NOME) 
VALUES ('Timon Willis');

INSERT INTO ARTISTA (NOME) 
VALUES ('Plato Diaz');

INSERT INTO ARTISTA (NOME) 
VALUES ('Marvin Berg');

INSERT INTO ARTISTA (NOME) 
VALUES ('Lyle Stanley');

INSERT INTO ARTISTA (NOME) 
VALUES ('Roanna Roth');

INSERT INTO ARTISTA (NOME) 
VALUES ('Garth Petty');

INSERT INTO ARTISTA (NOME) 
VALUES ('Aidan Carrillo');

INSERT INTO ARTISTA (NOME) 
VALUES ('Hedy Melton');

INSERT INTO ARTISTA (NOME) 
VALUES ('Thaddeus Mcguire');

INSERT INTO ARTISTA (NOME) 
VALUES ('Amos Boyd');

INSERT INTO ARTISTA (NOME) 
VALUES ('Rigel Graves');

INSERT INTO ARTISTA (NOME) 
VALUES ('Karyn Vincent');

INSERT INTO ARTISTA (NOME) 
VALUES ('Joan Eaton');

INSERT INTO ARTISTA (NOME) 
VALUES ('Alice King');

INSERT INTO ARTISTA (NOME) 
VALUES ('Lionel Rivas');

INSERT INTO ARTISTA (NOME) 
VALUES ('Hamish Chan');

INSERT INTO ARTISTA (NOME) 
VALUES ('Upton Schwartz');

INSERT INTO ARTISTA (NOME) 
VALUES ('Christian Chapman');

INSERT INTO ARTISTA (NOME) 
VALUES ('Curran Franco');

INSERT INTO ARTISTA (NOME) 
VALUES ('Dominique Harding');

INSERT INTO ARTISTA (NOME) 
VALUES ('Chiquita Patrick');

INSERT INTO ARTISTA (NOME) 
VALUES ('Linus Ramos');

INSERT INTO ARTISTA (NOME) 
VALUES ('Aspen Flowers');

INSERT INTO ARTISTA (NOME) 
VALUES ('Zenia Wooten');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Aftermath Entertainment');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Interscope Records');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Def Jam Recordings');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Death Row Records');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Amaru Entertainment');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Warner Records');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Bad Boy Records');

INSERT INTO GRAVADORA (NOME) 
VALUES ('G-Unit Records');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Disney Music Group');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Shady Records');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Doggystyle Records');

INSERT INTO GRAVADORA (NOME) 
VALUES ('Fox Music');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('chocalho');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('pandeiro');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('surdo');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('sino');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('triângulo');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('zabumba');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('ganzá');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('caixa');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('bombo');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('matraca');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('bateria');

INSERT INTO INSTRUMENTO (NOME) 
VALUES ('tamborim');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('Brit Awards');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('MTV Europe Video Awards');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('Grammy Awards');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('Mercury Prize');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('MTV MIAW');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('Billboard Music Awards');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('MTV Music Awards');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('GDI Music Awards');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('Billboard Women in Music');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('People’s Choice Awards');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('BET Awards');

INSERT INTO ORGANIZACAO (NOME) 
VALUES ('Multishow Brazilian Music Award');

CREATE OR REPLACE TRIGGER TRG_INSERE_MUSICA
BEFORE INSERT ON MUSICA
FOR EACH ROW
DECLARE
    V_GRAVADORA_ID GRAVADORA.ID%TYPE;
BEGIN
    SELECT ID INTO V_GRAVADORA_ID FROM GRAVADORA ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY;
    :NEW.ID := V_GRAVADORA_ID;
END;
/
/

INSERT INTO MUSICA (ID,NUM,NOME,GENERO) 
VALUES (4,3,'Câmeras','Pop');

INSERT INTO MUSICA (ID,NUM,NOME,GENERO) 
VALUES (0,2,'Ela','Forró');

INSERT INTO MUSICA (ID,NUM,NOME,GENERO) 
VALUES (3,5,'Quando lhe deu','Eletrônica');

INSERT INTO MUSICA (ID,NUM,NOME,GENERO) 
VALUES (5,6,'Declarava que João','Eletrônica');

INSERT INTO MUSICA (ID,NUM,NOME,GENERO) 
VALUES (5,7,'Se lembrou','Rock');

INSERT INTO MUSICA (ID,NUM,NOME,GENERO) 
VALUES (6,1,'Resposta','Funk');

INSERT INTO MUSICA (ID,NUM,NOME,GENERO) 
VALUES (3,4,'E chorou','Pop');

INSERT INTO MUSICA (ID,NUM,NOME,GENERO) 
VALUES (9,10,'Marasmo da fazenda','Reggae');

INSERT INTO MUSICA (ID,NUM,NOME,GENERO) 
VALUES (1,9,'Olhada no meu','Pop');

INSERT INTO MUSICA (ID,NUM,NOME,GENERO) 
VALUES (9,8,'Senhor de alta','Rap');

CREATE OR REPLACE TRIGGER TRG_INS_ADMIN 
BEFORE INSERT ON ADMIN_ 
FOR EACH ROW 
DECLARE 
V_ID_USUARIO VARCHAR(15); 
BEGIN 
SELECT CPF INTO V_ID_USUARIO 
FROM USUARIO 
WHERE CPF NOT IN (SELECT ID FROM ADMIN_) 
ORDER BY DBMS_RANDOM.VALUE 
FETCH FIRST 1 ROW ONLY; 
  :NEW.ID := V_ID_USUARIO; 
  END; 
/

INSERT INTO ADMIN_ (CARGO) 
VALUES ('Estudante');

INSERT INTO ADMIN_ (CARGO) 
VALUES ('Presidente');

INSERT INTO ADMIN_ (CARGO) 
VALUES ('Arquiteto');

INSERT INTO ADMIN_ (CARGO) 
VALUES ('Médico');

INSERT INTO ADMIN_ (CARGO) 
VALUES ('Designer');

INSERT INTO ADMIN_ (CARGO) 
VALUES ('Operador');

INSERT INTO ADMIN_ (CARGO) 
VALUES ('Analista');

INSERT INTO ADMIN_ (CARGO) 
VALUES ('Engenheiro');

CREATE OR REPLACE PROCEDURE INSERIR_COMUM AS 
  v_cpf VARCHAR(15); 
  contagem numeric := 17; 
BEGIN 
	FOR i IN 1..contagem LOOP 
  -- Busca um CPF que não esteja presente nas tabelas ADMIN ou COMUM 
  SELECT CPF INTO v_cpf 
  FROM USUARIO 
  WHERE CPF NOT IN (SELECT ID FROM ADMIN_ UNION SELECT ID FROM COMUM)
  FETCH FIRST 1 ROW ONLY;
 
  -- Se um CPF foi encontrado, faz o insert na tabela COMUM 
  IF v_cpf IS NOT NULL THEN 
    INSERT INTO COMUM(ID) VALUES (v_cpf); 
    DBMS_OUTPUT.PUT_LINE('CPF ' || v_cpf || ' inserido com sucesso na tabela COMUM.'); 
  ELSE 
    DBMS_OUTPUT.PUT_LINE('Todos os CPFs já estão cadastrados nas tabelas ADMIN ou COMUM.'); 
  END IF; 
  END LOOP; 
END; 
/

CREATE OR REPLACE PROCEDURE INSERE_CANTA AS
    ID_MUSICA MUSICA.ID%TYPE;
    NUM_MUSICA MUSICA.NUM%TYPE;
    ID_ARTISTA ARTISTA.ID%TYPE;
    contagem numeric := 20;
BEGIN
    FOR i IN 1..contagem LOOP
        SELECT ID, NUM INTO ID_MUSICA, NUM_MUSICA FROM MUSICA ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY;
        SELECT ID INTO ID_ARTISTA FROM ARTISTA ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY;

        BEGIN
            INSERT INTO CANTA (ID, NUM, ID_ART) VALUES (ID_MUSICA, NUM_MUSICA, ID_ARTISTA);
        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
                CONTINUE; 
        END;

    END LOOP;
END;
/
/

CREATE OR REPLACE PROCEDURE INSERE_CONSOME AS
    v_id MUSICA.ID%TYPE;
    v_num MUSICA.NUM%TYPE;
    v_cpf USUARIO.CPF%TYPE;
    contagem numeric := 20;
BEGIN
    FOR i IN 1..contagem LOOP
        -- seleciona aleatoriamente um ID e um NUM da tabela MUSICA
        SELECT ID, NUM INTO v_id, v_num FROM MUSICA ORDER BY dbms_random.value() FETCH FIRST 1 ROWS ONLY;

        -- seleciona aleatoriamente um CPF da tabela USUARIO
        SELECT CPF INTO v_cpf FROM USUARIO WHERE ROWNUM = 1 ORDER BY dbms_random.value();

        -- faz o insert na tabela CONSOME
        BEGIN
            INSERT INTO CONSOME (CPF, ID, NUM) VALUES (v_cpf, v_id, v_num);
            DBMS_OUTPUT.PUT_LINE('Insert realizado com sucesso');
        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
                DBMS_OUTPUT.PUT_LINE('Chave primária já existente, registro ignorado');
        END;
    END LOOP;
END;
/
/

CREATE OR REPLACE PROCEDURE INSERE_TOCA AS
  v_id_canta CANTA.ID%TYPE;
  v_id_mus CANTA.NUM%TYPE;
  v_id_num CANTA.ID_ART%TYPE;
  v_id_instr INSTRUMENTO.ID%TYPE;
BEGIN 
  -- Seleciona um registro aleatório da tabela CANTA 
  SELECT ID, NUM, ID_ART INTO v_id_canta, v_id_num ,v_id_mus FROM CANTA ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY; 
   
  -- Seleciona um registro aleatório da tabela INSTRUMENTO 
  SELECT ID INTO v_id_instr FROM INSTRUMENTO ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY; 
   
  -- Insere um novo registro na tabela TOCA 
  INSERT INTO TOCA (ID_CANTA, ID_INSTRUMENTO, ID_MUS, ID_NUM) VALUES (v_id_canta, v_id_instr, v_id_mus, v_id_num); 
   
  -- Exibe mensagem de sucesso 
  DBMS_OUTPUT.PUT_LINE('Registro inserido com sucesso!'); 
END;
/
/

CREATE OR REPLACE PROCEDURE INSERE_GANHA AS 
    v_id_categoria GANHA.ID_CATEGORIA%TYPE; 
    v_id_org GANHA.ID_ORGANIZACAO%TYPE; 
    v_id_mus GANHA.ID_MUSICA%TYPE; 
    v_id_num GANHA.ID_NUM%TYPE; 
	contagem numeric := 20; 
BEGIN 
 
	FOR i IN 1..contagem LOOP 
    SELECT ID INTO v_id_categoria 
    FROM CATEGORIA 
    ORDER BY DBMS_RANDOM.VALUE 
    FETCH FIRST 1 ROW ONLY; 
     
    SELECT ID INTO v_id_org 
    FROM ORGANIZACAO 
    ORDER BY DBMS_RANDOM.VALUE 
    FETCH FIRST 1 ROW ONLY; 
     
    SELECT ID, NUM INTO v_id_mus, v_id_num 
    FROM MUSICA 
    WHERE NUM IS NOT NULL 
    ORDER BY DBMS_RANDOM.VALUE 
    FETCH FIRST 1 ROW ONLY; 
     
    INSERT INTO GANHA (ID_CATEGORIA, ID_ORGANIZACAO, ID_MUSICA, ID_NUM) 
    VALUES (v_id_categoria, v_id_org, v_id_mus, v_id_num); 
     
    DBMS_OUTPUT.PUT_LINE('INSERT realizado com sucesso.'); 
	END LOOP; 
END; 
/

BEGIN 
INSERE_CONSOME;
INSERE_CANTA;
INSERIR_COMUM;
INSERE_TOCA;
INSERE_GANHA;
END;
/
